#+Title: Table of Contents
#+SETUPFILE: "../include/settings.org"
#+PROPERTY: header-args:html-chrome :flags --window-size=320,240 --force-device-scale-factor=2 :cache yes

* Course structure

Students should work through this material in the following order

* Preparation weeks

This work can be done outside the classroom.

- [[file:prep/week1/README.html][Week 1, getting familiar with tools]]

  Setting up some initial tools and getting to know VSCode.

- [[file:prep/week2/README.html][Week 2, initial HTML]]

  Introduces HTML and researching material on the Mozilla Developer Network.

* The course

This work should be done in the classroom, and is intended to be done in the following order.

- [[file:classroom/classroom-intro/README.html][Introduction to the classroom]]

  Initial material for day 1 in the classroom. You should update this to reference logistical information for your course.

- [[file:classroom/shell-and-git/README.html][Shell and Git]]

  Recap the shell material from week 1. First steps with Git, including creating a GitHub account, configuring Git locally, and introductory Git workflow.

- [[file:classroom/css/README.html][CSS]]

  Initial CSS material.

- [[file:classroom/advanced-css/README.html][Advanced CSS]]

  Advanced CSS material

- [[file:classroom/javascript/introduction/README.html][Introductory Javascript / DOM]]

  Up to here is approximately 4 weeks worth of material depending on how quickly the students move through it.

- [[file:classroom/javascript/shopping/README.html][Javascript Shopping List exercise]]

  This is several weeks worth of project and exercises where we will
  build a frontend application from the ground up, applying the material
  that has been covered in the previous weeks.

- [[file:classroom/javascript/ecosystem/README.html][Javascript Ecosystem]]

  Introduction to tools used in the JS Ecosystem -- Node and NPM, JS and CSS minimisers, Grunt for task automation, watching files for changes, etc.

- [[file:classroom/javascript/react/README.html][Javascript React]]

  Introduction to React, building the shopping list using React. Also includes material on OO inheritance.

- [[file:classroom/sql/README.html][SQL]]

  Introduction to SQL. This can be moved to other parts of the course or dropped, it's used if any of the internships require an intro to SQL.
